### ISSUE TITLE
Auto Figure Numbers

### ISSUE THREAD

**Issue by muirdata** [muirdata/muir-data#241]
For all photos that have the Include in Report box checked add a figure number (Figure 1:, Figure 2:, etc.) automatically in the caption.  This would be ideally added at the Report Builder level as well as the PDF report.

Bladefence request.

**Comment by muirdata** [comment]
At the moment, this appears to be working correctly.

![sadfghjkghikl](https://cloud.githubusercontent.com/assets/2980580/23582635/abd4dd5c-00e3-11e7-96f2-9c731546f51d.png)

**Comment by JohnKJohansen-MDS** [comment]
If you are satisfied with this in Staging, please "Close" this issue. If we have a problem moving forward, we can re-open it.
