### ISSUE TITLE
PDF File Name while Loading Report does not Match Downloaded File Name

### ISSUE THREAD

**Issue by muirdata** [muirdata/muir-data#298]
While the PDF is loading, a name appears at the top left that does not relate to the downloaded file name.  In this case, when the PDF is downloaded, the file name is **SIE PSK T08 Blade A 10-18-2015** and that is not what appears when viewing the report using the browser.

![untitled](https://cloud.githubusercontent.com/assets/2980580/12663420/f5f6a796-c5dc-11e5-8eca-980febe5c8fd.jpg)

**Comment by muirdata** [comment]
This was changed to Generated Report instead of the report name.  Appears to be working.

![rthjfjmkfjm](https://cloud.githubusercontent.com/assets/2980580/23582736/958b28b0-00e5-11e7-88aa-67da8c456f25.png)

**Comment by JohnKJohansen-MDS** [comment]
If you are satisfied with how this is functioning in Staging, please "Close"
