### ISSUE TITLE
Create New Damage Type Back Button & Language

### ISSUE THREAD

**Issue by muirdata** [muirdata/muir-data#300]
"Create New Damage Type" button is slightly misleading.  Perhaps it should say "Create Another Damage Type" because the original language makes it sound like the user did not create a damage type, but the first damage type was already created despite the language. 

![image](https://cloud.githubusercontent.com/assets/2980580/12801300/750b5d26-ca90-11e5-8230-b5951fca5f29.png)

There is no back "<" available if the "Create New Damage Type" button is accidentally selected.

![image](https://cloud.githubusercontent.com/assets/2980580/12801338/d5d6276c-ca90-11e5-82d6-5b3cc15f899b.png)

It would also be helpful to have "Blade Templates" button on this page as well.  Right now, the user has to use the menu on the top right to access the damage types that were just created in order to construct a template.

**Comment by JohnKJohansen-MDS** [comment]
![image](https://cloud.githubusercontent.com/assets/24964880/24133077/79762ed4-0db7-11e7-838c-83df6469d965.png)

**Comment by JohnKJohansen-MDS** [comment]
CHanged button text, added back button in Dev (bladedamagetypes/views, create.html and form.html)
