### ISSUE TITLE
Lock Environment After Work Order Creation

### ISSUE THREAD

**Issue by muirdata** [muirdata/muir-data#316]
Environment does not lock after work order creation. All other sections lock out correctly.          

![kunjnonkj](https://cloud.githubusercontent.com/assets/2980580/23567516/6dc3ef54-000b-11e7-8bf1-12beb3fdd040.png)

**Comment by muirdata** [comment]
This applies to any Work Order when it is locked.

**Comment by JohnKJohansen-MDS** [comment]
Fixed in staging. Reassigning to James for testing and (hopefully) closure

**Comment by muirdata** [comment]
Looks good.
