### ISSUE TITLE
Work Order Creation Autosave Error

### ISSUE THREAD

**Issue by muirdata** [muirdata/muir-data#317]
During Work Order creation (after hitting Save and Lock Work Order button) getting an Autosave error.

![asdfasdfas](https://cloud.githubusercontent.com/assets/2980580/23568335/dc7af7b4-000e-11e7-9bc1-3b1c11177cb1.png)

**Comment by muirdata** [comment]
This happens anytime a Work Order is created and locked.

**Comment by JohnKJohansen-MDS** [comment]
Correction pushed and tested in Staging. Reassigning to James for testing and (hopefully) closure.
