### ISSUE TITLE
Environment Units Not Showing in Damage Template

### ISSUE THREAD

**Issue by muirdata** [muirdata/muir-data#318]
Here are the units that were selected on the General tab of the Work Order. These should be the defaults within a damage template.

![xbn bncbn](https://cloud.githubusercontent.com/assets/2980580/23568584/035e55fa-0010-11e7-90df-bf16db55f325.png)

Below is what is showing up in a damage template. Environment defaults are not present.

![asdfasdfasdf](https://cloud.githubusercontent.com/assets/2980580/23568643/4ba00f8e-0010-11e7-9301-436e1dd75ee6.png)

**Comment by JohnKJohansen-MDS** [comment]
Verifying: This issue is the empty drop downs for the units next to the measurements.

Can you give me the work order id or number I can see this on?

**Comment by muirdata** [comment]
Yes, that is correct.  The units in Environment should default to what is defined under the General tab of the Work Order.

I did another test using Testing Fun 6 (Bird Strike defect) and it appeared to copy over previous data from another Work Order. I did not enter the measure numbers, then just appeared.  Should default to blank numbers (minus Start Time) and start with Lamination #1.

![image](https://cloud.githubusercontent.com/assets/2980580/23591884/ad0480aa-01ac-11e7-99fb-3872e770f7ec.png)


![image](https://cloud.githubusercontent.com/assets/2980580/23591880/a088982a-01ac-11e7-8967-a4ff2ee29398.png)

**Comment by JohnKJohansen-MDS** [comment]
I see how to get to the General settings, and I also see where the system is coded to copy any fields from your last work order. What I am not seeing is how to add a damage template to a work order. How do I get to the template screen?

**Comment by JohnKJohansen-MDS** [comment]
Added defect - I see it now

**Comment by JohnKJohansen-MDS** [comment]
The code is set to save environment variables each time Environment Variables are set. If you change to another work order, it will still set the variables to what you last used. It looks like this was a design feature so you could update multiple assets without remeasuring or retyping. When you leave the work order, the save environment remains intact, and will be auto-populated in the next work order (unless you log out and log back in). It looks like if you work on a template that doesn't use environments, these variables may get set to "empty" values. I fixed the original bug by checking if the values are emptry after loading from the saved enviroment, and resetting them to the workorder defaults if they are empty.

**Comment by JohnKJohansen-MDS** [comment]
Please verify - do we want to clear the saved environment settings if we navigate away from the work order, or do we want to always load the last used values (the latter is the way the system is currently coded)

**Comment by muirdata** [comment]
The variables should not be cleared when the User navigates away from the Work Order. Also, Environment on the General tab should lock when the Work Order is created similarly to Severity, Materials, etc. This sets the default units that are intended to be used on the tablet. Being able to change the default Units after Work Order creation could potentially cause problems later on when the tablet syncs.

**Comment by JohnKJohansen-MDS** [comment]
The variables are not cleared. A copy of the environment settings last entered is copied, effectively to a clipboard. If you add a new tempalte, the process is to 1) initialize from the work order, 2) copy the values from the clip board. The fix for this has been to add step 3 ) apply the work order defaults again if the clipboard values are invalid.

**Comment by JohnKJohansen-MDS** [comment]
Can we open a separate bug for locking default units? That is  avery different issue with very different regression testing.

**Comment by muirdata** [comment]
Understood.

Created issue #323

**Comment by muirdata** [comment]
This appears to be fixed now. The General Tab now matches the defaults in the damage templates.

From General Tab:

![image](https://cloud.githubusercontent.com/assets/2980580/24086636/6bf7345c-0cd0-11e7-9a1e-44290fab1dea.png)


From template:

![image](https://cloud.githubusercontent.com/assets/2980580/24086629/5972ffd2-0cd0-11e7-8346-533a395a80a1.png)
