### ISSUE TITLE
Manage Users Selection

### ISSUE THREAD

**Issue by muirdata** [muirdata/muir-data#322]
Under Manage Users, should be able to select a User by clicking anywhere in the within the highlighted rectangle. Right now the User has to click on the blue arrow to drill down into a User. This is the only place in the system that requires this specific of a click.

![image](https://cloud.githubusercontent.com/assets/2980580/23592221/722eca7a-01b2-11e7-90a2-9890338877d3.png)

**Comment by JohnKJohansen-MDS** [comment]
Corrected and tested in Staging - reassigning to James to test and (if successful) close

**Comment by muirdata** [comment]
Almost correct. You can now click on the highlighted rectangle and it will select the User. However, the cursor should be a hand with pointing index finger instead of an arrow whenever hovering over the rectangles. Right now the hand only shows up when hovering over the blue arrow that points to the right. Please take a look at other menus such as the Work Order list to see intended functionality.

**Comment by JohnKJohansen-MDS** [comment]
Now using cursor:pointer

**Comment by muirdata** [comment]
Will check once Users is functional.

**Comment by muirdata** [comment]
All better.
