### ISSUE TITLE
Environment Units Not Locking During Work Order Creation

### ISSUE THREAD

**Issue by muirdata** [muirdata/muir-data#323]
Environment Units should lock just like Severity, Materials, etc. when a Work Order is created.

![image](https://cloud.githubusercontent.com/assets/2980580/23828203/4c4edeb8-067f-11e7-9d8e-602ac753cef9.png)

**Comment by JohnKJohansen-MDS** [comment]
Duplicate of 316. Fixed in Staging, waiting for James to test and close

**Comment by muirdata** [comment]
Looks good.

![image](https://cloud.githubusercontent.com/assets/2980580/24069592/c5afa8ee-0b68-11e7-8db0-53fdec7848ea.png)
