### ISSUE TITLE
Can't Login to Staging

### ISSUE THREAD

**Issue by muirdata** [muirdata/muir-data#325]
Issue seems to have shown up after the Angular update. Can't test until the login problem is resolved.

![image](https://cloud.githubusercontent.com/assets/2980580/23835422/391a9206-0724-11e7-8bd1-1a61f206a5f1.png)

**Comment by JohnKJohansen-MDS** [comment]
Hmm. Backed us back down to Angular 1.4. I think we can log in now - profile is working. Please try

**Comment by muirdata** [comment]
Yes, that seems to have resolved the login issue. Thanks.
