### ISSUE TITLE
Asset Details Not All Showing

### ISSUE THREAD

**Issue by muirdata** [muirdata/muir-data#334]
Click on a Blade

![image](https://cloud.githubusercontent.com/assets/2980580/24089799/afbd69a0-0cf7-11e7-8050-92761a5374cc.png)

Here is what Staging looks like

![image](https://cloud.githubusercontent.com/assets/2980580/24089814/d1fc09b8-0cf7-11e7-8779-5fa2d33df1f2.png)

Compare the below from Production to what is shown above in Staging. **Staging should look like Production.**

![image](https://cloud.githubusercontent.com/assets/2980580/24089825/eabc3ff4-0cf7-11e7-8857-83ae8e0f3f94.png)

**Comment by JohnKJohansen-MDS** [comment]
![image](https://cloud.githubusercontent.com/assets/24964880/24131836/3440cca6-0dae-11e7-81cf-fca0641d494c.png)

**Comment by JohnKJohansen-MDS** [comment]
Unable to duplicate in staging - I followed your instructions, and in Staging this record looks like prod to me.

**Comment by muirdata** [comment]
I agree, I am having trouble reproducing it. I will keep trying while I am doing other testing and keep you posted.

**Comment by JohnKJohansen-MDS** [comment]
I am pretty sure this was a problem while I was trying to fix staging. I would close this - we can reopen it if it re-occurs.
